---
role:
  pkg:
    - curl
    # - fzf # $(brew --prefix)/opt/fzf/install
    - git
    - name: vim # -nox
      os: ["debian"]
    - name: vim
      os: ["darwin"]
      args:
        # - with-cscope
        - with-lua
        - with-luajit
        - with-override-system-vi
        - with-python
        # - with-pyhton3
        # - with-custom-python
        # - with-custom-ruby
  link:
    # - "[^.]*:.vim"
    # - "autoload/*:.vim/autoload"
    - "*.vim:.vim"
    - "autoload:.vim"
    - "config:.vim"
    - "ftdetect:.vim"
    - "ftplugin:.vim"
    - "plugin:.vim"
    - "syntax:.vim"
  line:
    ".vimrc": "source $HOME/.vim/init.vim"
    ".gvimrc": "source $HOME/.vim/ginit.vim"
