---
role:
  pkg:
    - name: curl
      action: install
    # - fzf # $(brew --prefix)/opt/fzf/install
    # - git
    - name: vim
      os: ["!darwin"]
    - name: vim
      os: ["darwin"]
      args:
        # - --with-cscope
        - --with-lua
        - --with-luajit
        - --with-override-system-vi
        - --with-python
        # - --with-pyhton3
        # - --with-custom-python
        # - --with-custom-ruby
    -  neovim
    # pip install neovim
    # pip3 install neovim
    # gem install neovim
    # npm install -g neovim 
    # - name: python-neovim
    #   os: ["arch", "darwin"]
  dir:
    - .vim
  link:
    # - "[^.]*:.vim"
    # - "autoload/*:.vim/autoload"
    - "*.vim:.vim"
    - "autoload:.vim"
    - "config:.vim"
    - "ftdetect:.vim"
    - "ftplugin:.vim"
    - "plugin:.vim"
    - "syntax:.vim"
  line:
    ".vimrc": "source $HOME/.vim/init.vim"
    ".gvimrc": "source $HOME/.vim/ginit.vim"
