---
role:
  pkg:
    - name: curl
      action: install
    # - fzf # $(brew --prefix)/opt/fzf/install
    # - git
    - name: vim
      os: ["!darwin"]
    - name: vim
      os: ["darwin"]
      args:
        # - --with-cscope
        - --with-lua
        - --with-luajit
        - --with-override-system-vi
        - --with-python
        # - --with-pyhton3
        # - --with-custom-python
        # - --with-custom-ruby

    # https://neovim.io/doc
    - neovim
    # https://github.com/neovim/node-client
    - name: neovim
      type: npm
    # https://github.com/neovim/python-client
    - name: neovim
      type: pip2
    - name: neovim
      type: pip3
    # - name: python-neovim
    #   os: ["arch", "darwin"]
    # https://github.com/alexgenco/neovim-ruby
    - name: neovim
      type: gem
      os: ["darwin"]

    # Linters (c.f. config/ale.vim)
    # - name: vim-vint
    #   type: pip3

    # Fixers
    - name: shfmt
      os: darwin

  dir:
    - .vim
  link:
    # - "[^.]*:.vim"
    # - "autoload/*:.vim/autoload"
    - "*.vim:.vim"
    - "autoload:.vim"
    - "config:.vim"
    - "ftdetect:.vim"
    - "ftplugin:.vim"
    - "plugin:.vim"
    - "syntax:.vim"
  line:
    ".vimrc": "source $HOME/.vim/init.vim"
    ".gvimrc": "source $HOME/.vim/ginit.vim"
  post_install:
    - vim --version
    - nvim --version
    - neovim-node-host
    - python2 -c 'import neovim'
    - python3 -c 'import neovim'
    - command: neovim-ruby-host
      os: ["darwin"]
