---
role:
  pkg:
    - curl
    # - name: git
    #   os: ["!debian"]
    # - name: git-core
    #   os: ["debian"]
    - vim
  link:
    # - "[^.]*:.vim"
    # - "autoload/*:.vim/autoload"
    - "*.vim:.vim"
    - "autoload:.vim"
    - "config:.vim"
    - "ftdetect:.vim"
    - "ftplugin:.vim"
    - "plugin:.vim"
  line:
    ".vimrc": "source $HOME/.vim/init.vim"
    ".gvimrc": "source $HOME/.vim/ginit.vim"
