---
role:
  pkg:
    - curl
    # - fzf # $(brew --prefix)/opt/fzf/install
    - git
    - vim
  link:
    # - "[^.]*:.vim"
    # - "autoload/*:.vim/autoload"
    - "*.vim:.vim"
    - "autoload:.vim"
    - "config:.vim"
    - "ftdetect:.vim"
    - "ftplugin:.vim"
    - "plugin:.vim"
    - "syntax:.vim"
  line:
    ".vimrc": "source $HOME/.vim/init.vim"
    ".gvimrc": "source $HOME/.vim/ginit.vim"
