dir: ".vim"
link: "[^.]*:.vim"
lines:
  - path: ".vimrc"
    line: "source ~/.vim/init.vim"
    # if filereadable(expand('~/.vim/init.vim')) | source ~/.vim/init.vim | endif
  - path: ".gvimrc"
    line: "source ~/.vim/ginit.vim"
    # if filereadable(expand('~/.vim/init.vim')) | source ~/.vim/init.vim | endif
